# PostgreSQL config Example
[database]
host = "localhost"
port = 8432
user = "postgres"
password = ""
dbname = "local"
sslmode = "disable"

# log config Example
[logger]
save_path = "./serverLog"
encoder_type = "json"
encode_level = "LowercaseLevelEncoder"
encode_caller = "ShortCallerEncoder"
